# This is a basic workflow to help you get started with Actions

name: CICD-prod
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a two jobs called "CI" and "CD"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it and sets up Python
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
          architecture: 'x64'
      # Set up pip - you can expand this with additional package installs that you would need for running unit tests (this is not included in this example)
      - run: |
          python -m pip install --upgrade pip==21.3.1
      # Code quality check
      - name: Code quality check
        run: |
          pip install flake8
          pip install flake8_formatter_junit_xml
          flake8 --exit-zero .
      # Archive notebook scripts
      - name: Archive files
        uses: actions/upload-artifact@v3
        with:
          name: scripts
          path: scripts/
  CD:
    needs: CI
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it and sets up Python
      - uses: actions/checkout@v3
      # Set up Python
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
          architecture: 'x64'
      # Install pip and install requirements for the release python file
      - run: |
          python -m pip install --upgrade pip
          pip install -r "./environment_setup/requirements.txt"
      # Deploy notebooks using a Python file 
      - name: Deploy notebooks to workspace
      # Set token and dbx_url as environment variables
        env:
          DBX_TOKEN: ${{secrets.DBX_TOKEN}}
          DBX_ORG_URL: ${{secrets.DBX_ORG_URL}}
      # Run the Python script
        run: |
          python db_service/notebooks_to_db_dev.py -source_path "./scripts" -target_path "/Production/scripts" -dbx_api_token $DBX_TOKEN -dbx_ws_url $DBX_ORG_URL
